FROM apache/airflow:2.10.5-python3.11

USER root
RUN apt-get update \
    && apt-get install --yes --no-install-recommends libgomp1 \
    && rm -rf /var/lib/apt/lists/*

USER airflow
COPY --chown=airflow:root pyproject.toml README.md /opt/airflow/project/
COPY --chown=airflow:root src /opt/airflow/project/src
RUN pip install --no-cache-dir "/opt/airflow/project" \
    && pip uninstall --yes \
        apache-airflow-providers-google \
        apache-airflow-providers-snowflake \
    && pip install --no-cache-dir \
        --index-url https://download.pytorch.org/whl/cpu \
        "torch==2.8.0"
COPY --chown=airflow:root scripts /opt/airflow/project/scripts
COPY --chown=airflow:root configs /opt/airflow/project/configs
COPY --chown=airflow:root airflow/dags /opt/airflow/dags
WORKDIR /opt/airflow/project
